### ISSUE TITLE
Issue with basic auth for github api

### ISSUE THREAD

**Issue by chrisdlangton** [fifemon/graphql-datasource#17]
Trying Github.com API https://developer.github.com/v4/guides/forming-calls/#authenticating-with-graphql

On Grafana v6.7.3 (a04ef6cefc)

Gettting

```
GraphQL Data Source plugin failed
Error: [$injector:unpr] Unknown provider: rProvider <- r http://errors.angularjs.org/1.6.9/$injector/unpr?p0=rProvider%20%3C-%20r
```

No idea what any of that means.

Basically you can do exactly what i did with a fresh install like this;

docker-compose.yaml

```
version: '3.6'
x-defaults: &defaults
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "3"
  cap_drop:
    - ALL
  cap_add:
    - DAC_OVERRIDE

services:
  dashboard:
    <<: *defaults
    image: bitnami/grafana:6-debian-10@sha256:bda98953d622ff2c10ffd0bcbf3c71eb7eaf3222281c5ab2dc5e3b2d2cafcc3e
    container_name: dashboard
    build:
      context: ./
      dockerfile: docker/Dockerfile
    user: "${UID}"
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
    ports:
     - 3000:3000
    volumes:
      - ./grafana-persistence:/opt/bitnami/grafana/data/
      - ./docker/grafana/conf/custom.ini:/opt/bitnami/grafana/conf/custom.ini
```

The `.env` like this

```
GF_SECURITY_ADMIN_PASSWORD=bitnami
GF_INSTALL_PLUGINS=graphql-datasource=https://github.com/fifemon/graphql-datasource/archive/v1.1.0.zip
UID=1000
```

Any help would be appreciated, happy to work on a fix myself and PR if i can get some guidance.
