### ISSUE TITLE
Setting up the data sources using GraphQL plug-in via environmental variables

### ISSUE THREAD

**Issue by olliefr** [fifemon/graphql-datasource#43]
Hello, 

A silly question as I'm not an expert in Grafana, but can I configure a data source using this plugin via environmental variables?

I can provision the plugin in `docker-compose` using the following snippet.

```
grafana:
  image: grafana/grafana:7.3.7
  environment:
    GF_INSTALL_PLUGINS: "fifemon-graphql-datasource"
```

Are there environmental variables I can set to configure this plugin for a specific data source using environmental variables in a similar fashion?

I know I can use a [provisioning file](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources) but was wondering if I can avoid having to fiddle with the file system 🙃

Thank you.
