### ISSUE TITLE
How to define HTTP headers in a graphql JSON datasource

### ISSUE THREAD

**Issue by hafeja** [fifemon/graphql-datasource#72]
Hello @retzkek ,

As Grafana user managing my Grafana instance as code I want to define a Grafana graphql datasource using this (btw: great 👍)  graphql plugin. For authentication, I need to configure a custom header containing a token.

![image](https://user-images.githubusercontent.com/59864250/135282646-8cf61d32-3321-494a-8755-e68cfaaf99b3.png)

How can I define those values in my [JSON datasource](https://grafana.com/docs/grafana/latest/http_api/data_source/#create-a-data-source)?

Following example doesn't work:
![image](https://user-images.githubusercontent.com/59864250/135283194-5e9fd3bd-c21b-41d8-906f-b094947991d9.png)

Any feedback appreciated!

**Comment by hafeja** [comment]
Hi,
I found the solution here: https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources 

```yaml
datasources:
  - name: Graphite
    jsonData:
      httpHeaderName1: 'HeaderName'
      httpHeaderName2: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'HeaderValue'
      httpHeaderValue2: 'Bearer XXXXXXXXX'
```
